import Head from 'next/head'
import Box from '@/components/Box'


export default function Home() {


  return (
    <>
      <Head>
        <title>Founded Max</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container   mx-auto  mt-32  bg-[#1e1f21]  px-10 py-5">
        <p className='text-gray-400 mb-5'>Goals Overview</p>
        <div className='grid md:grid-cols-2 sm:grid-cols-2 gap-4'>
          {/* box */}
          <Box />
          <Box />
          <Box />
          <Box />
        </div>

      </div>

    </>
  )
}
