import { useState } from "react"
import Head from 'next/head'
import Link from 'next/link'
import axios, { AxiosResponse } from "axios"
//import { useRouter } from 'next/router'

const Login = () => {

    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')
    //const router = useRouter()
    //const [data, setData] = useState<AxiosResponse | null | void>()
    // const uid = localStorage.getItem('uid');
    // const preRegister = async () => {
    //     try {
    //       const response = await axios.post("http://135.125.202.125:3001/api/get_goals?login=233141", {
    //       })
    //       if (response.status === 200) {
    //         localStorage.setItem('uid', response.data)
    //       }
    //     } catch (error) {
    //         console.error(error)
    //     }
    //   }
    
    // const handleClick = {
    //     if (data: any) {
    //         () => router.push('/profile')
    //     }
    // }
    //const preRegister = async () => {
    //    await axios.get("http://135.125.202.125:3001/api/get_goals?login=23231")
    //    .then(res => {
    //        setData(res)
    //    })
    //    .catch(err => {
    //        console.log(err);
    //    });
    //}
    

    return (
        <>
            <Head>
                <title>Funded Max</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container mx-auto my-5">
                <div className="grid grid-cols-1">
                    <div className="text-center mb-5">
                        <h1 className="h1">Login</h1>
                    </div>
                    <form action="">
                        <div>
                            <input
                                className="block py-2.5 w-full text-sm  bg-transparent border border-b rounded-lg px-2    "
                                value={username}
                                onChange={(e) => setUsername(e.target.value)}
                                type="text"
                                placeholder="userName" />
                        </div>
                        <div>
                            <input
                                className="block mt-5 py-2.5 w-full text-sm  bg-transparent border border-b rounded-lg px-2    "
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                type="password"
                                placeholder="password" />
                        </div>
                        <Link href="/profile">
                            <button
                                className="btn border w-full rounded-lg py-1 bg-blue-300 text-black mt-5"
                            >
                                Login
                            </button>
                        </Link>
                        <Link href="/">
                            <button
                                className="btn border w-full rounded-lg py-1 bg-blue-300 text-black mt-5"
                                //onClick={() => {data && router.push('/profile')}}
                            >
                                back
                            </button>
                        </Link>
                    </form>
                </div>
            </div>
        </>
    )
}

export default Login
